rework orphan deletion
gardener/machine-controller-manager-provider-openstack pull request #65
Opened 2022-07-04 19:30 UTC by kon-angelo

**What this PR does / why we need it**:

Similar to https://github.com/gardener/machine-controller-manager-provider-aws/pull/85

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement developer
probeResources() now doesn't try to delete orphan resources but only lists them.
The beforeSuite for IT test now calls for cleanup of orphan resources separately.
The Integration Test, which looks for orphan resources, now doesn't try to delete the orphan resources and just waits for them to be done automatically.
```

2022-07-04 19:30 UTC, kon-angelo commented
/invite @himanshu-kun

2022-07-11 08:11 UTC, himanshu-kun requested changes

2022-07-11 08:11 UTC, himanshu-kun commented on test/integration/provider/openstack.go
> +			orphans = append(orphans, port.ID)
we don't want to delete the resources in the `getOrpahnedInstances, getOrphanedDisks, getOrphanedNics` function, but just list and return them.

2022-07-11 08:11 UTC, himanshu-kun commented on test/integration/provider/openstack.go
> +			orphans = append(orphans, port.ID)
like this https://github.com/gardener/machine-controller-manager-provider-aws/blob/1fe8064940be21d1df564002525ea8677a13e776/test/integration/provider/aws.go#L158-L160

2022-07-11 08:11 UTC, himanshu-kun commented on test/integration/provider/rti.go
> +		fmt.Printf("The following resources are orphans ... trying to delete them \n")
```suggestion
		fmt.Printf("The following resources are orphans ... waiting for them to be deleted \n")
```

2022-07-11 11:00 UTC, himanshu-kun approved these changes
thanks for the changes
/lgtm

2022-07-11 11:07 UTC, merged

2022-07-12 07:49 UTC, kon-angelo commented
/fixes https://github.com/gardener/machine-controller-manager-provider-openstack/issues/58